apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Value.name }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx 
  rules:
    - host: {{ .Values.global.host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Value.name }}
                port:
                  name: http
